In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:/Amazon Customer Analysis/amazon_ecommerce_1M.csv')

In [3]:
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,04-03-2025,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,12-12-2025,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,25-04-2024,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,18-12-2025,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,16-05-2024,5,Delhi,Web,UPI,False,Delayed

In [4]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'], format = '%d-%m-%Y')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              999967 non-null   float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       999975 non-null   float64
 13  purchase_date       1000000 non-null  datetime64[ns]
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(5), int64(3), object(10)
memory usage: 145.9+ MB

In [6]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,purchase_date,shipping_time_days
count,1000000.000000,1000000.000000,1000000.000000,999967.000000,1000000.000000,1000000.000000,999975.000000,1000000,1000000.000000
mean,13224.119093,28.996161,9938.876985,3.927224,32.626704,250.023345,3.750031,2025-03-30 23:32:00.384000256,3.166389
min,200.030000,5.000000,101.460000,1.500000,0.000000,0.000000,2.500000,2024-03-31 00:00:00,1.000000
25%,2700.147500,16.910000,1705.930000,3.600000,10.000000,125.000000,3.100000,2024-09-29 00:00:00,2.000000
50%,4971.830000,28.070000,3790.795000,3.900000,20.000000,250.000000,3.800000,2025-03-31 00:00:00,3.000000
75%,14134.482500,39.240000,10384.440000,4.300000,39.000000,375.000000,4.400000,2025-09-30 00:00:00,5.000000
max,79999.700000,70.000000,75831.110000,5.000000,3408.000000,500.000000,5.000000,2026-03-31 00:00:00,6.000000
std,18079.626921,14.681077,14271.885557,0.519444,43.382201,144.567038,0.722092,NaN,1.674178

In [7]:
df.isnull().sum()

user_id                0
product_id             0
category               0
subcategory            0
brand                  0
price                  0
discount               0
final_price            0
rating                33
review_count           0
stock                  0
seller_id              0
seller_rating         25
purchase_date          0
shipping_time_days     0
location               0
device                 0
payment_method         0
is_returned            0
delivery_status        0
dtype: int64

In [8]:
df['rating'] = df.groupby(['category','subcategory', 'brand'])['rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df['seller_rating'] = df.groupby(['category','subcategory','brand'])['seller_rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [11]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'location', 'device', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='object')

In [12]:
df.rename(columns = {'location':'city',
                    'device': 'device_type'}, inplace = True)

In [13]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'city', 'device_type', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='object')

In [15]:
!pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\sahil\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [16]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "Sankalp7*" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "amazon_customer_analysis"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'amazon_customer_analysis'.